### ISSUE TITLE
app running, but not posting data, erroring

### ISSUE THREAD

**Issue by wanman** [zonque/AlRide#8]
https://wunderride.herokuapp.com/entries?locale=en

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by zonque** [comment]
As you are the application owner, did you check the logs for more information?

**Comment by wanman** [comment]
2017-02-21T15:20:49.095809+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2017-02-21T15:20:49.095809+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
2017-02-21T15:20:49.095812+00:00 app[worker.1]: (See full trace by running task with --trace)
2017-02-21T15:20:49.198977+00:00 heroku[worker.1]: State changed from up to crashed
2017-02-21T15:20:49.199782+00:00 heroku[worker.1]: State changed from crashed to starting
2017-02-21T15:20:52.708485+00:00 heroku[worker.1]: Starting process with command `bundle exec rake jobs:work`
2017-02-21T15:20:52.480301+00:00 app[web.1]: [2017-02-21 15:20:52] INFO  WEBrick 1.3.1
2017-02-21T15:20:52.480333+00:00 app[web.1]: [2017-02-21 15:20:52] INFO  ruby 2.2.6 (2016-11-15) [x86_64-linux]
2017-02-21T15:20:52.480658+00:00 app[web.1]: [2017-02-21 15:20:52] INFO  WEBrick::HTTPServer#start: pid=4 port=22303
2017-02-21T15:20:52.789926+00:00 heroku[web.1]: State changed from starting to up
2017-02-21T15:20:53.347511+00:00 heroku[worker.1]: State changed from starting to up
2017-02-21T15:20:57.082057+00:00 app[worker.1]: rake aborted!
2017-02-21T15:20:57.082092+00:00 app[worker.1]: Don't know how to build task 'jobs:work' (see --tasks)
2017-02-21T15:20:57.082592+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
2017-02-21T15:20:57.082594+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
2017-02-21T15:20:57.082595+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-02-21T15:20:57.082595+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
2017-02-21T15:20:57.082596+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
2017-02-21T15:20:57.082597+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-02-21T15:20:57.082598+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-02-21T15:20:57.082599+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
2017-02-21T15:20:57.082599+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
2017-02-21T15:20:57.082600+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
2017-02-21T15:20:57.082601+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
2017-02-21T15:20:57.082602+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
2017-02-21T15:20:57.082602+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
2017-02-21T15:20:57.082603+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
2017-02-21T15:20:57.082604+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2017-02-21T15:20:57.082605+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
2017-02-21T15:20:57.082609+00:00 app[worker.1]: (See full trace by running task with --trace)
2017-02-21T15:20:57.192064+00:00 heroku[worker.1]: Process exited with status 1
2017-02-21T15:20:57.203203+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by zonque** [comment]
From the top of my head, I cannot tell what's going on. Where does this `jobs:work` thing come from? It's not in the sources at least.

**Comment by zonque** [comment]
I'm closing this issue as there was no reply to my last comment.
